build:
  image: python:2.7
  commands:
    - XDG_CACHE_HOME=/drone/pip-cache pip install ./
    - python setup.py test

cache:
  mount:
    - dashboard/static/dashboard/node_modules
    - /drone/pip-cache

publish:
  pypi:
    repository: https://pypi.python.org/pypi
    username: sourcelair
    password: $$SOURCELAIR_PYPI_PASSWORD
    distributions:
      - sdist
    when:
      event: tag
  github_release:
    files: ./...
    checksum: sha256
    when:
      event: tag
