pipeline:
  build:
    image: python:2.7
    commands:
      - pip install ./
      - python setup.py test

  publish:
    image: akalipetis/drone-pypi
    repository: https://pypi.python.org/pypi
    username: sourcelair
    password: ${SOURCELAIR_PYPI_PASSWORD}
    distributions:
      - sdist
    when:
      event: tag
